# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e087c08e2d7f809eee0f2bafcc7305928b845ecc126dee601ab1f4c2166877df366b77e74baf370f16076ab5d0151a4c8382596c707dff86f3e92d1796d1379

test:
  secret_key_base: 00ffe2f2f3a2e4b8a6e61bb829bff86d90255f0dedb43d2955ab5537d86804d4bb09bd86c720a9d9ac23955f6bfef956c035aa78b6455261add96b0ca28d3736

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
